resolution_settings: 
    - id: 0
      name: "HD"
      image_width: 1280
      image_height: 720
    - id: 1
      name: "FullHD"
      image_width: 1920
      image_height: 1080
    - id: 2
      name: "Four_K"
      image_width: 3840
      image_height: 2160
