- '/pos_ctl/kp'
- '/pos_ctl/ki'
- '/pos_ctl/kd'
- '/att_ctl/kp'
- '/att_ctl/kd'
- '/ctl/tolerance_pos'
- '/ctl/tolerance_att'
- '/ctl/duration_goal'
- '/led_display_left/gains'
- '/led_display_right/gains'
- '/sensor_fusion/Q_position_diag_x'
- '/sensor_fusion/Q_position_diag_v'
- '/sensor_fusion/R_position_diag_x'
- '/sensor_fusion/R_position_diag_v'
- '/sensor_fusion/Q_angle_diag_q'
- '/sensor_fusion/Q_angle_diag_b'
- '/sensor_fusion/R_angle_diag'
