<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>airflow</name>
  <version>0.0.0</version>
  <description>Airflow disturbance plugin for Gazebo Harmonic</description>
  <maintainer email="jaxa.doe@example.com">JAXA</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>ament_index_cpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sim_msgs</depend>
  <depend>coordinate_transform</depend>
  <depend>gz_sim_vendor</depend>
  <depend>gz_plugin_vendor</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
