#ifndef PLATFORM_MSGS_H
#define PLATFORM_MSGS_H

//#include "actionlib_msgs/GoalID.h"
//#include "std_msgs/Bool.h"
//#include "std_msgs/ColorRGBA.h"
//#include "std_msgs/Empty.h"
#include "std_msgs/Time.h"
#include "std_msgs/UInt8.h"
#include "std_msgs/UInt16.h"
//#include "geometry_msgs/WrenchStamped.h"
#include "platform_msgs/CameraStatus.h"
#include "platform_msgs/ContainerStatus.h"
#include "platform_msgs/ManagerStatus.h"
#include "platform_msgs/MicrophoneStatus.h"
#include "platform_msgs/Mode.h"
#include "platform_msgs/MonitorStatus.h"
#include "platform_msgs/NodeStatusValue.h"
#include "platform_msgs/OperationType.h"
#include "platform_msgs/PowerStatus.h"
#include "platform_msgs/SetOperationType.h"
#include "platform_msgs/UserLogic.h"
#include "platform_msgs/UserLogicCommand.h"
#include "platform_msgs/UserLogicCommandRequest.h"
#include "platform_msgs/UserLogicCommandResponse.h"
#include "platform_msgs/UserNodeCommand.h"
#include "platform_msgs/UserNodeCommandRequest.h"
#include "platform_msgs/UserNodeCommandResponse.h"
#include "platform_msgs/UserNodeStatus.h"

#endif // PLATFORM_MSGS_H
